-- Generated by seed-to-sql.mjs from seed-content.json. Idempotent.

insert into public.temas (slug, nombre, descripcion, orden)
values ('introduccion-ia', 'Introducción a los sistemas inteligentes y la IA', 'Recorrido por los fundamentos, la historia y la evolución de la inteligencia artificial: qué es un sistema inteligente, la diferencia entre IA débil y fuerte, y los enfoques que buscan que las máquinas piensen o actúen de forma racional o como humanos. Introduce el Test de Turing, los niveles evolutivos de la IA y la noción de agente inteligente.', 1)
on conflict (slug) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion, orden = excluded.orden;

insert into public.temas (slug, nombre, descripcion, orden)
values ('resolucion-problemas-busqueda', 'Resolución de problemas y búsqueda', 'Técnicas que permiten a un agente formular un problema en términos de estados y acciones y explorar sistemáticamente el espacio de estados para hallar una secuencia que lleve al objetivo. Incluye árboles de búsqueda, búsqueda ciega y heurística (A*) y algoritmos adversariales como minimax y poda alfa-beta en juegos de dos jugadores.', 2)
on conflict (slug) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion, orden = excluded.orden;

insert into public.temas (slug, nombre, descripcion, orden)
values ('representacion-conocimiento', 'Representación del conocimiento y razonamiento', 'Estudia cómo codificar información sobre el mundo en estructuras que una computadora pueda usar para razonar. Abarca la jerarquía dato-información-conocimiento, la lógica y los sistemas de reglas, las ontologías y la distinción entre conocimiento declarativo y procedimental, base de los sistemas expertos y la web semántica.', 3)
on conflict (slug) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion, orden = excluded.orden;

insert into public.temas (slug, nombre, descripcion, orden)
values ('aprendizaje-automatico', 'Aprendizaje automático', 'Conjunto de técnicas mediante las cuales un sistema mejora su desempeño a partir de los datos, sin ser programado explícitamente para cada tarea. Comprende el aprendizaje supervisado, no supervisado y por refuerzo, con algoritmos como la regresión, los árboles de decisión, k-medias o Q-learning.', 4)
on conflict (slug) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion, orden = excluded.orden;

insert into public.temas (slug, nombre, descripcion, orden)
values ('redes-neuronales-deep-learning', 'Redes neuronales y aprendizaje profundo', 'Subcampo del aprendizaje automático inspirado en el sistema nervioso, basado en neuronas artificiales interconectadas mediante pesos y funciones de activación. Las redes profundas, con múltiples capas, permiten abstraer representaciones de alto nivel para resolver problemas complejos de visión, lenguaje y voz.', 5)
on conflict (slug) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion, orden = excluded.orden;

insert into public.temas (slug, nombre, descripcion, orden)
values ('reconocimiento-patrones-pln', 'Reconocimiento de patrones y procesamiento del lenguaje natural', 'Aplica el aprendizaje automático y profundo para percibir y clasificar señales del mundo real: imágenes, voz y texto. Cubre el ciclo de reconocimiento (sensado, segmentación, extracción de características y clasificación), las redes convolucionales, el reconocimiento del habla y el procesamiento del lenguaje natural.', 6)
on conflict (slug) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion, orden = excluded.orden;

insert into public.criterios_si (slug, nombre, descripcion, orden)
select 'alcance-capacidad', 'Alcance y capacidad', 'Clasifica la IA según la amplitud de tareas que puede resolver, desde sistemas especializados hasta una hipotética inteligencia general.', 1
where not exists (select 1 from public.criterios_si where slug = 'alcance-capacidad');

insert into public.criterios_si (slug, nombre, descripcion, orden)
select 'russell-norvig', 'Modelos de Russell y Norvig', 'Las cuatro visiones clásicas de la IA según el cruce pensar/actuar y humano/racional.', 2
where not exists (select 1 from public.criterios_si where slug = 'russell-norvig');

insert into public.criterios_si (slug, nombre, descripcion, orden)
select 'evolucion-hintze', 'Evolución (Arend Hintze)', 'Niveles evolutivos de la IA según su capacidad de memoria, comprensión y conciencia.', 3
where not exists (select 1 from public.criterios_si where slug = 'evolucion-hintze');

insert into public.criterios_si (slug, nombre, descripcion, orden)
select 'tipo-aprendizaje', 'Tipo de aprendizaje (Machine Learning)', 'Cómo el sistema aprende a partir de los datos: con o sin etiquetas, por refuerzo o en profundidad.', 4
where not exists (select 1 from public.criterios_si where slug = 'tipo-aprendizaje');

insert into public.criterios_si (slug, nombre, descripcion, orden)
select 'paradigma-representacion', 'Paradigma de representación del conocimiento', 'Cómo se representa el conocimiento: con símbolos y reglas explícitas o de forma implícita en estructuras matemáticas.', 5
where not exists (select 1 from public.criterios_si where slug = 'paradigma-representacion');

insert into public.criterios_si (slug, nombre, descripcion, orden)
select 'naturaleza-conocimiento', 'Naturaleza y forma del conocimiento', 'Clasifica el conocimiento según su grado de abstracción, su expresabilidad y su contenido u objetivo.', 6
where not exists (select 1 from public.criterios_si where slug = 'naturaleza-conocimiento');

insert into public.criterios_si (slug, nombre, descripcion, orden)
select 'metodo-adquisicion', 'Método de adquisición del conocimiento', 'Cómo se obtiene el conocimiento: transferido por expertos humanos (deductivo) o extraído de datos y ejemplos (inductivo).', 7
where not exists (select 1 from public.criterios_si where slug = 'metodo-adquisicion');

-- DESTRUCTIVE: removes all old clasificacion_si rows and their dependent valoraciones.
-- User-gated — applied only after explicit OK (S1-T09).
truncate public.clasificaciones_si cascade;

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'ia-debil-estrecha', 'IA Débil (o Estrecha)', 'Diseñada para realizar tareas específicas y limitadas. No posee comprensión general del mundo. Es el tipo de IA utilizado actualmente.', null, 'Siri, Alexa, sistemas de reconocimiento de voz, recomendadores de contenido.', 'null'::jsonb, 1
where not exists (select 1 from public.clasificaciones_si where slug = 'ia-debil-estrecha');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'ia-fuerte-general', 'IA Fuerte (IAG)', 'Capaz de realizar cualquier tarea intelectual que pueda realizar un ser humano. Razonamiento general, adaptación y aprendizaje amplio. Actualmente es un concepto teórico.', null, '(concepto teórico — sin ejemplos implementados)', 'null'::jsonb, 2
where not exists (select 1 from public.clasificaciones_si where slug = 'ia-fuerte-general');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'sistemas-que-piensan-como-humanos', 'Sistemas que piensan como humanos', 'Según Russell y Norvig, este enfoque busca que las máquinas reproduzcan los procesos cognitivos humanos: cómo razonamos, tomamos decisiones y resolvemos problemas. Se apoya en la psicología cognitiva y la neurociencia para modelar la mente humana computacionalmente, siendo la base de la IA cognitiva y de los modelos de memoria y atención.', null, 'Sistemas de razonamiento analógico, modelos computacionales de la memoria humana, arquitecturas cognitivas como ACT-R.', '[{"titulo":"Artificial Intelligence: A Modern Approach — Sitio oficial AIMA","url":"https://aima.cs.berkeley.edu/"},{"titulo":"What is AI? The four schools of thought — Medium / Otto Lang","url":"https://otto-lang.medium.com/what-is-ai-an-explanation-by-the-4-different-schools-of-thought-74a85ebecda2"}]'::jsonb, 1
where not exists (select 1 from public.clasificaciones_si where slug = 'sistemas-que-piensan-como-humanos');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'sistemas-que-actuan-como-humanos', 'Sistemas que actúan como humanos', 'Este enfoque, también de Russell y Norvig, se centra en producir comportamientos indistinguibles de los humanos, independientemente de si el proceso interno es igual al humano. La prueba de Turing es el referente clásico de este paradigma. Incluye la robótica social, los avatares conversacionales y los sistemas de imitación de comportamiento humano.', null, 'Chatbots como ELIZA, robots humanoides sociales, asistentes de voz que imitan entonación humana.', '[{"titulo":"Artificial Intelligence: A Modern Approach — Sitio oficial AIMA","url":"https://aima.cs.berkeley.edu/"},{"titulo":"What is AI? The four schools of thought — Medium / Otto Lang","url":"https://otto-lang.medium.com/what-is-ai-an-explanation-by-the-4-different-schools-of-thought-74a85ebecda2"}]'::jsonb, 2
where not exists (select 1 from public.clasificaciones_si where slug = 'sistemas-que-actuan-como-humanos');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'sistemas-que-piensan-racionalmente', 'Sistemas que piensan racionalmente', 'Este enfoque busca formalizar el razonamiento correcto mediante la lógica y las matemáticas, siguiendo leyes de inferencia válidas para llegar a conclusiones garantizadas. Se basa en la tradición logicista de la filosofía y la matemática. Está en la base de los planificadores automáticos, los sistemas de demostración de teoremas y la programación lógica.', null, 'Prolog y sus motores de inferencia, demostradores automáticos de teoremas (Coq, Lean), planificadores PDDL.', '[{"titulo":"Artificial Intelligence: A Modern Approach — Sitio oficial AIMA","url":"https://aima.cs.berkeley.edu/"},{"titulo":"Logic and Artificial Intelligence — Stanford Encyclopedia of Philosophy","url":"https://plato.stanford.edu/entries/logic-ai/"}]'::jsonb, 3
where not exists (select 1 from public.clasificaciones_si where slug = 'sistemas-que-piensan-racionalmente');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'sistemas-que-actuan-racionalmente', 'Sistemas que actúan racionalmente', 'Es el enfoque preferido por Russell y Norvig: el agente racional actúa para maximizar su rendimiento esperado dado su conocimiento y sus capacidades, sin importar si lo hace exactamente como un humano o siguiendo un razonamiento lógico puro. Este paradigma unifica la teoría de decisiones, el aprendizaje por refuerzo y los agentes inteligentes.', null, 'Agentes de aprendizaje por refuerzo (AlphaGo, motores de ajedrez), robots autónomos, sistemas de recomendación.', '[{"titulo":"Artificial Intelligence: A Modern Approach — Sitio oficial AIMA","url":"https://aima.cs.berkeley.edu/"},{"titulo":"What is AI? The four schools of thought — Medium / Otto Lang","url":"https://otto-lang.medium.com/what-is-ai-an-explanation-by-the-4-different-schools-of-thought-74a85ebecda2"}]'::jsonb, 4
where not exists (select 1 from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'maquinas-reactivas', 'Máquinas Reactivas', 'No poseen memoria. Responden únicamente al estado actual del entorno. No aprenden de experiencias pasadas.', null, 'Deep Blue.', 'null'::jsonb, 1
where not exists (select 1 from public.clasificaciones_si where slug = 'maquinas-reactivas');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'memoria-limitada', 'Memoria Limitada', 'Utilizan información reciente para mejorar sus decisiones. Aprenden de experiencias previas.', null, 'Vehículos autónomos.', 'null'::jsonb, 2
where not exists (select 1 from public.clasificaciones_si where slug = 'memoria-limitada');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'teoria-de-la-mente', 'Teoría de la Mente', 'Comprenderían emociones, intenciones y necesidades humanas. Aún no existen plenamente.', null, '(concepto teórico)', 'null'::jsonb, 3
where not exists (select 1 from public.clasificaciones_si where slug = 'teoria-de-la-mente');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'autoconciencia', 'Autoconciencia', 'Poseerían conciencia de sí mismas y de su existencia. Concepto teórico.', null, '(concepto teórico)', 'null'::jsonb, 4
where not exists (select 1 from public.clasificaciones_si where slug = 'autoconciencia');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'aprendizaje-supervisado', 'Aprendizaje Supervisado', 'Aprende mediante datos etiquetados. Conoce previamente las respuestas correctas.', null, 'Filtros de spam, predicción de precios, diagnóstico asistido.', 'null'::jsonb, 1
where not exists (select 1 from public.clasificaciones_si where slug = 'aprendizaje-supervisado');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'aprendizaje-no-supervisado', 'Aprendizaje No Supervisado', 'Trabaja con datos sin etiquetar. Busca patrones y agrupaciones ocultas.', null, 'Clustering.', 'null'::jsonb, 2
where not exists (select 1 from public.clasificaciones_si where slug = 'aprendizaje-no-supervisado');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'aprendizaje-semi-supervisado', 'Aprendizaje Semi-supervisado', 'Combina datos etiquetados y no etiquetados. Reduce la necesidad de etiquetar grandes volúmenes.', null, 'Clasificación de páginas web con pocas etiquetas, reconocimiento de voz con audio parcialmente transcrito, detección de fraude con pocos casos confirmados.', 'null'::jsonb, 3
where not exists (select 1 from public.clasificaciones_si where slug = 'aprendizaje-semi-supervisado');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'aprendizaje-por-refuerzo', 'Aprendizaje por Refuerzo', 'Aprende mediante recompensas y castigos. Busca maximizar una recompensa acumulada.', null, 'AlphaGo.', 'null'::jsonb, 4
where not exists (select 1 from public.clasificaciones_si where slug = 'aprendizaje-por-refuerzo');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'deep-learning', 'Aprendizaje Profundo (Deep Learning)', 'Subcampo del ML. Redes neuronales profundas con múltiples capas.', null, 'Visión por computadora, PLN, reconocimiento de voz.', 'null'::jsonb, 5
where not exists (select 1 from public.clasificaciones_si where slug = 'deep-learning');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'ia-simbolica', 'IA Simbólica', 'La IA Simbólica representa el conocimiento mediante unidades discretas y explícitas: reglas lógicas, fórmulas, relaciones y símbolos manipulables. El razonamiento se lleva a cabo aplicando operaciones formales sobre estas estructuras, de manera que las decisiones pueden explicarse paso a paso. Es el paradigma dominante desde los orígenes de la IA hasta fines del siglo XX.', 'https://upload.wikimedia.org/wikipedia/commons/5/52/Chess_Programming.svg', 'Sistemas expertos médicos como MYCIN, demostradores automáticos de teoremas, planificadores lógicos como STRIPS.', '[{"titulo":"Inteligencia artificial simbólica — Wikipedia","url":"https://es.wikipedia.org/wiki/Inteligencia_artificial_simb%C3%B3lica"},{"titulo":"Logic and Artificial Intelligence — Stanford Encyclopedia of Philosophy","url":"https://plato.stanford.edu/entries/logic-ai/"}]'::jsonb, 1
where not exists (select 1 from public.clasificaciones_si where slug = 'ia-simbolica');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'ia-subsimbolica', 'IA Sub-simbólica', 'La IA Sub-simbólica (o no simbólica) codifica el conocimiento de forma implícita, distribuida en los pesos y parámetros de estructuras como las redes neuronales. En lugar de reglas explícitas, el sistema aprende representaciones internas a partir de grandes cantidades de datos. Esta aproximación es la base del deep learning y es más robusta ante datos ruidosos o incompletos.', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg', 'Redes neuronales convolucionales para visión artificial, modelos de lenguaje como GPT, redes recurrentes para series temporales.', '[{"titulo":"Symbolic vs. Sub-symbolic AI — Wikipedia (Symbolic AI, sección de contraste)","url":"https://en.wikipedia.org/wiki/Symbolic_artificial_intelligence"},{"titulo":"Red neuronal artificial — Wikipedia en español","url":"https://es.wikipedia.org/wiki/Red_neuronal_artificial"}]'::jsonb, 2
where not exists (select 1 from public.clasificaciones_si where slug = 'ia-subsimbolica');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'conocimiento-teorico', 'Conocimiento Teórico', 'Basado en teorías, modelos y generalizaciones. Busca explicar fenómenos. (dimensión: grado de abstracción)', null, 'Las leyes de Newton aplicadas a simulación física, un modelo matemático del clima, la teoría de grafos para optimización de rutas.', 'null'::jsonb, 1
where not exists (select 1 from public.clasificaciones_si where slug = 'conocimiento-teorico');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'conocimiento-empirico', 'Conocimiento Empírico', 'Basado en la experiencia directa y la observación. Surge de casos prácticos. (dimensión: grado de abstracción)', null, 'Datos de sensores de una planta industrial, registros históricos de ventas, observaciones clínicas acumuladas.', 'null'::jsonb, 2
where not exists (select 1 from public.clasificaciones_si where slug = 'conocimiento-empirico');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'conocimiento-explicito', 'Conocimiento Explícito', 'Fácil de documentar, almacenar y transmitir. (dimensión: expresabilidad)', null, 'Manuales, procedimientos, bases de conocimiento.', 'null'::jsonb, 3
where not exists (select 1 from public.clasificaciones_si where slug = 'conocimiento-explicito');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'conocimiento-tacito', 'Conocimiento Tácito', 'Difícil de expresar formalmente. Basado en experiencia e intuición. (dimensión: expresabilidad)', null, 'Reconocer una cara familiar.', 'null'::jsonb, 4
where not exists (select 1 from public.clasificaciones_si where slug = 'conocimiento-tacito');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'conocimiento-declarativo', 'Conocimiento Declarativo', 'Describe hechos, conceptos o relaciones. Responde qué es verdadero o falso (¿Qué?). (dimensión: contenido y objetivo)', null, 'Una base de hechos (''París es la capital de Francia''), una ontología de productos, una red semántica de relaciones.', 'null'::jsonb, 5
where not exists (select 1 from public.clasificaciones_si where slug = 'conocimiento-declarativo');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'conocimiento-procedimental', 'Conocimiento Procedimental', 'Describe procesos y métodos. Explica cómo realizar una tarea (¿Cómo?). (dimensión: contenido y objetivo)', null, 'El algoritmo de ordenamiento de una lista, los pasos de un protocolo de diagnóstico, una receta paso a paso.', 'null'::jsonb, 6
where not exists (select 1 from public.clasificaciones_si where slug = 'conocimiento-procedimental');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'aprendizaje-deductivo', 'Aprendizaje Deductivo', 'El conocimiento es transferido directamente por expertos humanos. Característico de los sistemas expertos. Basado en reglas definidas manualmente.', null, 'Sistemas expertos como MYCIN, motores de reglas de negocio, bases de conocimiento con reglas if-then definidas por especialistas.', 'null'::jsonb, 1
where not exists (select 1 from public.clasificaciones_si where slug = 'aprendizaje-deductivo');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'aprendizaje-inductivo', 'Aprendizaje Inductivo', 'El sistema extrae conocimiento a partir de datos y ejemplos. Característico de Machine Learning, redes neuronales, minería de datos.', null, 'Un clasificador de spam entrenado con miles de correos, un modelo de visión que aprende de ejemplos etiquetados, árboles de decisión sobre datos históricos.', 'null'::jsonb, 2
where not exists (select 1 from public.clasificaciones_si where slug = 'aprendizaje-inductivo');

-- Wire criterio_id for all 25 categories (UPDATE after both insert blocks).
update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'alcance-capacidad')
where slug = 'ia-debil-estrecha';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'alcance-capacidad')
where slug = 'ia-fuerte-general';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'russell-norvig')
where slug = 'sistemas-que-piensan-como-humanos';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'russell-norvig')
where slug = 'sistemas-que-actuan-como-humanos';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'russell-norvig')
where slug = 'sistemas-que-piensan-racionalmente';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'russell-norvig')
where slug = 'sistemas-que-actuan-racionalmente';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'evolucion-hintze')
where slug = 'maquinas-reactivas';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'evolucion-hintze')
where slug = 'memoria-limitada';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'evolucion-hintze')
where slug = 'teoria-de-la-mente';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'evolucion-hintze')
where slug = 'autoconciencia';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'tipo-aprendizaje')
where slug = 'aprendizaje-supervisado';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'tipo-aprendizaje')
where slug = 'aprendizaje-no-supervisado';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'tipo-aprendizaje')
where slug = 'aprendizaje-semi-supervisado';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'tipo-aprendizaje')
where slug = 'aprendizaje-por-refuerzo';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'tipo-aprendizaje')
where slug = 'deep-learning';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'paradigma-representacion')
where slug = 'ia-simbolica';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'paradigma-representacion')
where slug = 'ia-subsimbolica';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'naturaleza-conocimiento')
where slug = 'conocimiento-teorico';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'naturaleza-conocimiento')
where slug = 'conocimiento-empirico';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'naturaleza-conocimiento')
where slug = 'conocimiento-explicito';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'naturaleza-conocimiento')
where slug = 'conocimiento-tacito';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'naturaleza-conocimiento')
where slug = 'conocimiento-declarativo';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'naturaleza-conocimiento')
where slug = 'conocimiento-procedimental';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'metodo-adquisicion')
where slug = 'aprendizaje-deductivo';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'metodo-adquisicion')
where slug = 'aprendizaje-inductivo';

-- DESTRUCTIVE: removes the 16 retired software rows and their dependent data.
-- User-gated — applied only after explicit OK (S1-T09).
-- valoraciones (no FK) are deleted first; software_clasificaciones cascade automatically.
delete from public.valoraciones
where contenido_tipo = 'software'
  and contenido_id in (select id from public.software where slug <> all(array['chatgpt', 'teachable-machine', 'gymnasium', 'stockfish', 'or-tools', 'protege', 'swi-prolog', 'scikit-learn', 'weka', 'orange', 'tensorflow', 'pytorch', 'opencv', 'whisper', 'hugging-face']));

delete from public.software where slug <> all(array['chatgpt', 'teachable-machine', 'gymnasium', 'stockfish', 'or-tools', 'protege', 'swi-prolog', 'scikit-learn', 'weka', 'orange', 'tensorflow', 'pytorch', 'opencv', 'whisper', 'hugging-face']);

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'chatgpt', (select id from public.temas where slug = 'introduccion-ia'),
  'ChatGPT', 'Generar respuestas conversacionales en lenguaje natural a partir de las indicaciones del usuario, asistiendo en tareas de redacción, consulta, programación y aprendizaje.', 'ChatGPT es un asistente conversacional basado en inteligencia artificial desarrollado por OpenAI, construido sobre modelos de lenguaje de gran escala de la familia GPT. Permite mantener diálogos en lenguaje natural para responder preguntas, redactar y resumir textos, traducir, escribir y depurar código, entre otras tareas. Se accede a través de una interfaz web y dispone de versiones gratuitas y de pago.', 'https://chatgpt.com/', 'Propietaria (gratuita con límites)', 2022, 'OpenAI', 'https://www.youtube.com/watch?v=3u1k7Jyn434', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/ChatGPT-Logo.svg'
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'teachable-machine', (select id from public.temas where slug = 'introduccion-ia'),
  'Google Teachable Machine', 'Permite crear modelos de aprendizaje automático (para reconocer imágenes, sonidos y posturas) de forma rápida y sin necesidad de programar.', 'Google Teachable Machine es una herramienta web gratuita desarrollada por Google Creative Lab que facilita la creación de modelos de aprendizaje automático sin requerir conocimientos de programación. Funciona en el navegador mediante TensorFlow.js y permite entrenar clasificadores de imágenes, sonidos y poses a partir de la cámara web, el micrófono o archivos cargados por el usuario. Los modelos resultantes se pueden exportar para integrarlos en sitios web y aplicaciones.', 'https://teachablemachine.withgoogle.com/', 'Apache 2.0', 2017, 'Google Creative Lab', 'https://www.youtube.com/watch?v=wU4ARWLp4sU', null
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'gymnasium', (select id from public.temas where slug = 'resolucion-problemas-busqueda'),
  'Gymnasium (ex OpenAI Gym)', 'Proporciona una API estandarizada y una colección de entornos de referencia para desarrollar, comparar y evaluar algoritmos de aprendizaje por refuerzo.', 'Gymnasium es una biblioteca de código abierto que define una interfaz estándar para crear e interactuar con entornos de aprendizaje por refuerzo (reinforcement learning). Es el sucesor mantenido de OpenAI Gym, gestionado por la Farama Foundation, e incluye una amplia variedad de entornos de referencia como CartPole, Atari y simulaciones robóticas. Permite que los agentes aprendan mediante prueba y error a través de funciones bien definidas como reset() y step().', 'https://gymnasium.farama.org/', 'MIT', 2022, 'Farama Foundation (originalmente OpenAI)', 'https://www.youtube.com/watch?v=Y_UqXz6aqfY', null
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'stockfish', (select id from public.temas where slug = 'resolucion-problemas-busqueda'),
  'Stockfish', 'Analizar partidas de ajedrez y calcular las mejores jugadas mediante un motor de búsqueda y evaluación de posiciones de código abierto.', 'Stockfish es uno de los motores de ajedrez de código abierto más potentes del mundo, capaz de evaluar posiciones y proponer las mejores jugadas con una fuerza muy superior a la de los grandes maestros humanos. Escrito en C++ y compatible con el protocolo UCI, se integra en numerosas plataformas y programas de ajedrez para analizar partidas y entrenar jugadores de todos los niveles. Desde 2020 incorpora redes neuronales (NNUE) que mejoran de forma notable la precisión de su evaluación.', 'https://stockfishchess.org/', 'GPL v3', 2008, 'Tord Romstad, Marco Costalba, Joona Kiiski, Gary Linscott y la comunidad de Stockfish', 'https://www.youtube.com/watch?v=ZSf8Sp76qp8', 'https://upload.wikimedia.org/wikipedia/commons/3/3a/NewLogoSF.png'
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'or-tools', (select id from public.temas where slug = 'resolucion-problemas-busqueda'),
  'Google OR-Tools', 'Resolver problemas de optimización combinatoria, como enrutamiento, planificación, asignación y programación lineal y de restricciones, encontrando la mejor solución entre un gran conjunto de posibilidades.', 'Google OR-Tools es una suite de software libre y de código abierto desarrollada por Google para la investigación de operaciones y la optimización combinatoria. Incluye solucionadores para programación lineal (LP), programación de enteros mixtos (MIP), programación de restricciones (CP) y enrutamiento de vehículos (VRP), entre otros. Escrita en C++, permite modelar problemas también desde Python, Java y C#, y se aplica en logística, planificación de horarios y asignación de recursos.', 'https://developers.google.com/optimization?hl=es-419', 'Apache 2.0', 2010, 'Google (autor original Laurent Perron)', 'https://www.youtube.com/watch?v=XPiDrFl5S84', null
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'protege', (select id from public.temas where slug = 'representacion-conocimiento'),
  'Protégé', 'Permite crear, editar y gestionar ontologías y bases de conocimiento mediante lenguajes estándar como OWL y RDF.', 'Protégé es un editor de ontologías gratuito y de código abierto desarrollado en la Universidad de Stanford. Permite construir representaciones formales del conocimiento de un dominio utilizando estándares de la Web Semántica como OWL y RDF, y se integra con razonadores de lógica descriptiva. Está disponible como aplicación de escritorio (Protégé Desktop) y en una versión colaborativa basada en navegador (WebProtégé).', 'https://protege.stanford.edu/', 'BSD 2-Clause', 1999, 'Universidad de Stanford (Stanford Center for Biomedical Informatics Research)', 'https://www.youtube.com/watch?v=N_uOC8xWWBE', 'https://upload.wikimedia.org/wikipedia/commons/7/72/Prot%C3%A9g%C3%A9_Logo.gif'
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'swi-prolog', (select id from public.temas where slug = 'representacion-conocimiento'),
  'SWI-Prolog', 'Proporcionar un entorno completo y de código abierto para programar en el lenguaje lógico Prolog, basado en hechos, reglas y consultas.', 'SWI-Prolog es una de las implementaciones de código abierto más utilizadas del lenguaje de programación lógico Prolog. Incluye un intérprete, un entorno de desarrollo con depurador, bibliotecas extensas y herramientas multiplataforma para Windows, Linux y macOS. Se emplea ampliamente en la enseñanza y en aplicaciones de inteligencia artificial, procesamiento de lenguaje natural, sistemas expertos y web semántica.', 'https://www.swi-prolog.org/', 'BSD 2-Clause', 1987, 'Jan Wielemaker (Universidad de Ámsterdam) y comunidad de SWI-Prolog', 'https://www.youtube.com/watch?v=WagksXYJXPY', 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Screenshot_of_SWI_prolog_icon.png'
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'scikit-learn', (select id from public.temas where slug = 'aprendizaje-automatico'),
  'scikit-learn', 'Proporcionar herramientas eficientes y de código abierto para el análisis de datos y el aprendizaje automático en Python, abarcando clasificación, regresión, agrupamiento y reducción de dimensionalidad.', 'scikit-learn es una biblioteca de código abierto para aprendizaje automático en el lenguaje Python, construida sobre NumPy, SciPy y Matplotlib. Ofrece una interfaz consistente con algoritmos para tareas de clasificación, regresión, agrupamiento, reducción de dimensionalidad, selección de modelos y preprocesamiento de datos. Es ampliamente utilizada en investigación, educación y aplicaciones industriales por su simplicidad y documentación extensa.', 'https://scikit-learn.org/', 'BSD 3-Clause', 2010, 'Proyecto scikit-learn (iniciado por David Cournapeau; comunidad de contribuyentes)', 'https://www.youtube.com/watch?v=qUjIybMkXBs', 'https://upload.wikimedia.org/wikipedia/commons/0/05/Scikit_learn_logo_small.svg'
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'weka', (select id from public.temas where slug = 'aprendizaje-automatico'),
  'Weka', 'Reúne algoritmos de aprendizaje automático y herramientas de minería de datos para preparar datos, clasificar, regresionar, agrupar, encontrar reglas de asociación y visualizar resultados.', 'Weka (Waikato Environment for Knowledge Analysis) es una colección de software de aprendizaje automático y minería de datos desarrollada en la Universidad de Waikato, Nueva Zelanda. Ofrece una interfaz gráfica (Explorer, Experimenter, KnowledgeFlow) y una línea de comandos para aplicar técnicas de clasificación, regresión, agrupamiento, selección de atributos y visualización sobre conjuntos de datos. Es uno de los entornos educativos de minería de datos más utilizados.', 'https://ml.cms.waikato.ac.nz/weka', 'GNU GPL', 1993, 'Machine Learning Group, Universidad de Waikato (Nueva Zelanda)', 'https://www.youtube.com/watch?v=N6itjmU3qeA', 'https://upload.wikimedia.org/wikipedia/commons/0/07/Weka_%28software%29_logo.png'
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'orange', (select id from public.temas where slug = 'aprendizaje-automatico'),
  'Orange Data Mining', 'Permite realizar análisis de datos, minería de datos y aprendizaje automático mediante programación visual, conectando bloques (widgets) en un lienzo sin necesidad de escribir código.', 'Orange Data Mining es una suite de software libre de código abierto para visualización de datos, análisis exploratorio, minería de datos y aprendizaje automático. Su interfaz de programación visual permite construir flujos de trabajo arrastrando y conectando componentes llamados widgets, lo que la hace accesible tanto para principiantes como para usuarios avanzados. Está desarrollada en Python y C++, y sus funciones pueden ampliarse con complementos especializados.', 'https://orangedatamining.com/?lang=es', 'GPL v3', 1996, 'Bioinformatics Laboratory, Universidad de Liubliana (Eslovenia)', 'https://www.youtube.com/watch?v=1inAFE3qftw', null
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'tensorflow', (select id from public.temas where slug = 'redes-neuronales-deep-learning'),
  'TensorFlow', 'Construir, entrenar y desplegar modelos de aprendizaje automático y redes neuronales mediante grafos de cálculo numérico.', 'TensorFlow es una biblioteca de código abierto para el aprendizaje automático y el aprendizaje profundo, desarrollada por Google. Permite definir y ejecutar cálculos numéricos sobre grafos de flujo de datos, facilitando la creación y el entrenamiento de redes neuronales. Es escalable a múltiples CPU y GPU y ofrece APIs para Python, JavaScript y otros lenguajes.', 'https://www.tensorflow.org/?hl=es', 'Apache 2.0', 2015, 'Google Brain Team', 'https://www.youtube.com/watch?v=bwvf25qmLWM', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/TensorFlow_logo.svg/250px-TensorFlow_logo.svg.png'
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'pytorch', (select id from public.temas where slug = 'redes-neuronales-deep-learning'),
  'PyTorch', 'Construir, entrenar y desplegar redes neuronales y modelos de aprendizaje profundo mediante cálculo con tensores y diferenciación automática.', 'PyTorch es una biblioteca de código abierto para aprendizaje automático y aprendizaje profundo basada en Python. Ofrece cálculo con tensores acelerado por GPU, grafos de cómputo dinámicos y un sistema de diferenciación automática que facilita la creación y el entrenamiento de redes neuronales. Cuenta con un amplio ecosistema de herramientas y es ampliamente utilizada tanto en investigación como en producción.', 'https://pytorch.org/', 'BSD 3-Clause', 2016, 'Meta AI (actualmente PyTorch Foundation, Linux Foundation)', 'https://www.youtube.com/watch?v=QetoD5LXlEg', 'https://upload.wikimedia.org/wikipedia/commons/c/c6/PyTorch_logo_black.svg'
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'opencv', (select id from public.temas where slug = 'reconocimiento-patrones-pln'),
  'OpenCV', 'Procesar imágenes y videos para tareas de visión por computadora, como detección de objetos, reconocimiento facial y análisis de imágenes en tiempo real.', 'OpenCV (Open Source Computer Vision Library) es una biblioteca de código abierto orientada a la visión por computadora y el aprendizaje automático. Ofrece miles de algoritmos para procesar imágenes y videos, detectar y reconocer objetos y rostros, y desarrollar aplicaciones de visión artificial. Es multiplataforma y cuenta con interfaces para lenguajes como C++, Python y Java.', 'https://opencv.org/', 'Apache 2.0', 1999, 'Intel (actualmente OpenCV.org / OpenCV Foundation)', 'https://www.youtube.com/watch?v=Nh1eob7tsr0', 'https://upload.wikimedia.org/wikipedia/commons/d/d2/OpenCV_logo_black.svg'
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'whisper', (select id from public.temas where slug = 'reconocimiento-patrones-pln'),
  'Whisper (OpenAI)', 'Transcribir y traducir automáticamente audio hablado a texto en múltiples idiomas mediante un modelo de reconocimiento automático del habla.', 'Whisper es un modelo de reconocimiento automático del habla (ASR) de código abierto desarrollado por OpenAI, entrenado con 680.000 horas de datos multilingües y multitarea. Convierte audio en texto con alta precisión, incluso en entornos ruidosos y con acentos variados, y admite tareas de transcripción, traducción e identificación de idioma. Se distribuye como código y pesos de modelo bajo licencia MIT, lo que permite su uso local y privado.', 'https://github.com/openai/whisper', 'MIT', 2022, 'OpenAI', 'https://www.youtube.com/watch?v=n2x43tA-hzI', 'https://upload.wikimedia.org/wikipedia/commons/6/66/OpenAI_logo_2025_%28symbol%29.svg'
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'hugging-face', (select id from public.temas where slug = 'reconocimiento-patrones-pln'),
  'Hugging Face', 'Plataforma colaborativa de código abierto para compartir, descubrir y desplegar modelos de inteligencia artificial, conjuntos de datos y aplicaciones de aprendizaje automático.', 'Hugging Face es una plataforma y comunidad de código abierto dedicada al aprendizaje automático, frecuentemente descrita como el "GitHub de la inteligencia artificial". A través de su Hub permite alojar y compartir cientos de miles de modelos preentrenados, conjuntos de datos y demostraciones interactivas (Spaces). Además mantiene bibliotecas ampliamente utilizadas, como Transformers, Datasets y Diffusers, que facilitan el desarrollo de aplicaciones de IA.', 'https://huggingface.co/', 'Apache 2.0', 2016, 'Hugging Face, Inc. (Clément Delangue, Julien Chaumond y Thomas Wolf)', 'https://www.youtube.com/watch?v=jG4Ns63tTeo', 'https://upload.wikimedia.org/wikipedia/commons/d/d6/Hf-logo-with-title.svg'
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

-- DESTRUCTIVE: removes retired temas (and cascades their progreso_roadmap rows).
-- User-gated. Runs after the software upsert because software.tema_id is RESTRICT.
delete from public.temas where slug <> all(array['introduccion-ia', 'resolucion-problemas-busqueda', 'representacion-conocimiento', 'aprendizaje-automatico', 'redes-neuronales-deep-learning', 'reconocimiento-patrones-pln']);

-- Junction: software_clasificaciones (M2M, one row per tool × category).
insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-como-humanos')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'memoria-limitada')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-supervisado')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-por-refuerzo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'deep-learning')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'ia-subsimbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-inductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-empirico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-tacito')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'teachable-machine'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'teachable-machine'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'teachable-machine'),
  (select id from public.clasificaciones_si where slug = 'memoria-limitada')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'teachable-machine'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-supervisado')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'teachable-machine'),
  (select id from public.clasificaciones_si where slug = 'deep-learning')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'teachable-machine'),
  (select id from public.clasificaciones_si where slug = 'ia-subsimbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'teachable-machine'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-inductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'teachable-machine'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-empirico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'teachable-machine'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'gymnasium'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'gymnasium'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'gymnasium'),
  (select id from public.clasificaciones_si where slug = 'memoria-limitada')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'gymnasium'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-por-refuerzo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'gymnasium'),
  (select id from public.clasificaciones_si where slug = 'ia-subsimbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'gymnasium'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-inductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'gymnasium'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-empirico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'gymnasium'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'stockfish'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'stockfish'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'stockfish'),
  (select id from public.clasificaciones_si where slug = 'maquinas-reactivas')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'stockfish'),
  (select id from public.clasificaciones_si where slug = 'ia-simbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'stockfish'),
  (select id from public.clasificaciones_si where slug = 'ia-subsimbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'stockfish'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-deductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'stockfish'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'stockfish'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-teorico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'or-tools'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'or-tools'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'or-tools'),
  (select id from public.clasificaciones_si where slug = 'maquinas-reactivas')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'or-tools'),
  (select id from public.clasificaciones_si where slug = 'ia-simbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'or-tools'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-deductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'or-tools'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'or-tools'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-teorico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'protege'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'protege'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-piensan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'protege'),
  (select id from public.clasificaciones_si where slug = 'maquinas-reactivas')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'protege'),
  (select id from public.clasificaciones_si where slug = 'ia-simbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'protege'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-deductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'protege'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-declarativo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'protege'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-explicito')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'swi-prolog'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'swi-prolog'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-piensan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'swi-prolog'),
  (select id from public.clasificaciones_si where slug = 'maquinas-reactivas')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'swi-prolog'),
  (select id from public.clasificaciones_si where slug = 'ia-simbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'swi-prolog'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-deductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'swi-prolog'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-declarativo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'swi-prolog'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'swi-prolog'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-explicito')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'scikit-learn'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'scikit-learn'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'scikit-learn'),
  (select id from public.clasificaciones_si where slug = 'memoria-limitada')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'scikit-learn'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-supervisado')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'scikit-learn'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-no-supervisado')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'scikit-learn'),
  (select id from public.clasificaciones_si where slug = 'ia-subsimbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'scikit-learn'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-inductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'scikit-learn'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-empirico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'scikit-learn'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'weka'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'weka'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'weka'),
  (select id from public.clasificaciones_si where slug = 'memoria-limitada')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'weka'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-supervisado')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'weka'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-no-supervisado')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'weka'),
  (select id from public.clasificaciones_si where slug = 'ia-subsimbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'weka'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-inductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'weka'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-empirico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'weka'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'orange'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'orange'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'orange'),
  (select id from public.clasificaciones_si where slug = 'memoria-limitada')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'orange'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-supervisado')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'orange'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-no-supervisado')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'orange'),
  (select id from public.clasificaciones_si where slug = 'ia-subsimbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'orange'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-inductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'orange'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-empirico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'orange'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'memoria-limitada')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'deep-learning')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-supervisado')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'ia-subsimbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-inductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-empirico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'pytorch'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'pytorch'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'pytorch'),
  (select id from public.clasificaciones_si where slug = 'memoria-limitada')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'pytorch'),
  (select id from public.clasificaciones_si where slug = 'deep-learning')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'pytorch'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-supervisado')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'pytorch'),
  (select id from public.clasificaciones_si where slug = 'ia-subsimbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'pytorch'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-inductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'pytorch'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-empirico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'pytorch'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'maquinas-reactivas')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-supervisado')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'deep-learning')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'ia-subsimbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-inductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-empirico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'memoria-limitada')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-supervisado')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'deep-learning')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'ia-subsimbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-inductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-empirico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'hugging-face'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'hugging-face'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-como-humanos')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'hugging-face'),
  (select id from public.clasificaciones_si where slug = 'memoria-limitada')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'hugging-face'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-supervisado')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'hugging-face'),
  (select id from public.clasificaciones_si where slug = 'deep-learning')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'hugging-face'),
  (select id from public.clasificaciones_si where slug = 'ia-subsimbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'hugging-face'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-inductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'hugging-face'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-empirico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'hugging-face'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;

-- Publicaciones (blog entries, idempotent by slug).
insert into public.publicaciones (slug, titulo, cuerpo, imagen_url, video_url, enlaces, tema_id, clasificacion_si_id, estado)
values (
  'que-es-un-sistema-inteligente', '¿Qué es un sistema inteligente?', 'Un sistema inteligente es un programa o dispositivo capaz de percibir su entorno, procesar esa información y actuar de manera que maximiza la probabilidad de alcanzar sus objetivos. A diferencia de un programa tradicional, no sigue únicamente una secuencia fija de instrucciones: puede adaptarse, aprender y tomar decisiones en situaciones que no fueron explícitamente programadas.

La inteligencia artificial es el campo de la informática que estudia y construye estos sistemas. Desde sus orígenes en la década de 1950, la IA ha pasado por múltiples ciclos de entusiasmo y escepticismo, pero en las últimas dos décadas el avance en poder de cómputo y la disponibilidad de grandes volúmenes de datos han transformado ideas teóricas en aplicaciones concretas.

Hoy, los sistemas inteligentes están presentes en el reconocimiento de voz de tu teléfono, en los algoritmos que ordenan tu feed de noticias y en los modelos que asisten a médicos en el diagnóstico de imágenes. Entender qué son y cómo funcionan es el primer paso para usarlos con criterio.',
  null, null, '[{"titulo":"Inteligencia artificial — Wikipedia en español","url":"https://es.wikipedia.org/wiki/Inteligencia_artificial"},{"titulo":"Artificial Intelligence: A Modern Approach — Sitio oficial AIMA","url":"https://aima.cs.berkeley.edu/"}]'::jsonb,
  (select id from public.temas where slug = 'introduccion-ia'),
  null,
  'publicado'
)
on conflict (slug) do nothing;

insert into public.publicaciones (slug, titulo, cuerpo, imagen_url, video_url, enlaces, tema_id, clasificacion_si_id, estado)
values (
  'como-aprende-una-maquina', 'Cómo aprende una máquina: una introducción al aprendizaje automático', 'Cuando hablamos de que una máquina "aprende", no nos referimos a que adquiere conciencia ni que comprende el mundo como lo hace una persona. Lo que ocurre es más preciso: el sistema ajusta sus parámetros internos a partir de ejemplos, de forma que mejora su desempeño en una tarea sin que nadie le haya dado la respuesta exacta para cada caso nuevo.

El aprendizaje automático (machine learning) engloba tres grandes paradigmas. En el aprendizaje supervisado, el sistema recibe pares de entrada y salida etiquetados —por ejemplo, miles de fotos de gatos y perros con su etiqueta correspondiente— y aprende a generalizar para clasificar imágenes que nunca ha visto. En el aprendizaje no supervisado, no hay etiquetas: el algoritmo busca patrones y agrupaciones por sí solo. Y en el aprendizaje por refuerzo, el agente aprende mediante prueba y error, recibiendo recompensas cuando toma buenas decisiones.

Entender estos paradigmas es fundamental antes de entrar en redes neuronales o modelos de lenguaje. Son los cimientos conceptuales sobre los que se construye todo lo demás, y confundirlos lleva a elegir la herramienta equivocada para el problema.',
  null, null, '[{"titulo":"Aprendizaje automático — Wikipedia en español","url":"https://es.wikipedia.org/wiki/Aprendizaje_autom%C3%A1tico"},{"titulo":"Machine Learning — Google Developers","url":"https://developers.google.com/machine-learning/crash-course/ml-intro"}]'::jsonb,
  (select id from public.temas where slug = 'aprendizaje-automatico'),
  null,
  'publicado'
)
on conflict (slug) do nothing;

insert into public.publicaciones (slug, titulo, cuerpo, imagen_url, video_url, enlaces, tema_id, clasificacion_si_id, estado)
values (
  'ia-debil-en-la-vida-cotidiana', 'La IA Débil que usás todos los días', 'La IA Débil —también llamada IA Estrecha o Narrow AI— es el tipo de inteligencia artificial que existe hoy. No es débil en el sentido de ser poco capaz: puede superar a cualquier humano en la tarea específica para la que fue diseñada. Es "débil" porque no puede trasladar ese conocimiento a otro dominio.

Cuando le pedís a tu teléfono que reconozca una canción, cuando Netflix te recomienda una serie, cuando el correo filtra el spam antes de que lo veas, o cuando el GPS recalcula la ruta en tiempo real: todos esos son ejemplos de IA Débil en acción. Cada uno de esos sistemas es extraordinariamente especializado y completamente incapaz de hacer lo que hace el de al lado.

Reconocer esto importa porque desmitifica la IA y te da una perspectiva más realista sobre lo que la tecnología puede y no puede hacer hoy. La IA Fuerte —un sistema con capacidades cognitivas generales como las humanas— sigue siendo un concepto teórico, no una realidad presente.',
  null, null, '[{"titulo":"IA débil — Wikipedia en español","url":"https://es.wikipedia.org/wiki/Inteligencia_artificial_d%C3%A9bil"}]'::jsonb,
  null,
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha'),
  'publicado'
)
on conflict (slug) do nothing;

insert into public.publicaciones (slug, titulo, cuerpo, imagen_url, video_url, enlaces, tema_id, clasificacion_si_id, estado)
values (
  'bienvenidos-al-blog-ia-dex', 'Bienvenidos al blog de ia-dex', 'Este blog nace con un propósito concreto: acercar los conceptos de la inteligencia artificial a quienes están dando sus primeros pasos en el campo, sin sacrificar el rigor ni caer en la simplificación vacía. Cada artículo va a estar anclado en un tema o clasificación del catálogo de ia-dex, de modo que lo que leas acá tenga un correlato directo con el software, los conceptos y los recursos que encontrás en la plataforma.

Lo que vas a encontrar acá son explicaciones de conceptos fundamentales, análisis de herramientas, contexto histórico y reflexiones sobre el impacto de la IA en distintos ámbitos. No vamos a seguir el hype ni a publicar por publicar: cada entrada tiene que sumar algo real a tu comprensión del campo.

Si acabás de llegar a ia-dex, te recomendamos empezar por el tema "Introducción a los sistemas inteligentes y la IA" en el catálogo. Y si tenés preguntas, sugerencias o querés que cubramos algún tema en particular, estamos atentos.',
  null, null, '[]'::jsonb,
  null,
  null,
  'publicado'
)
on conflict (slug) do nothing;

insert into public.publicaciones (slug, titulo, cuerpo, imagen_url, video_url, enlaces, tema_id, clasificacion_si_id, estado)
values (
  'roadmap-2026-borrador', 'Roadmap 2026 (borrador)', 'Este es un borrador interno de las mejoras planificadas para ia-dex durante 2026. El contenido aquí es provisional y no representa un compromiso público.

Entre las iniciativas en evaluación se encuentran la incorporación de nuevos temas al catálogo —con foco en ética de la IA y sistemas multiagente—, la expansión de la sección de software con herramientas de visión por computadora y PLN, y la posibilidad de abrir un espacio de contribuciones de la comunidad para enriquecer las descripciones y ejemplos.

Este artículo permanecerá en estado de borrador hasta que el roadmap esté confirmado. No es visible en el feed público.',
  null, null, '[]'::jsonb,
  null,
  null,
  'borrador'
)
on conflict (slug) do nothing;
