// Generates db/seed.sql from db/seed-content.json.
// temas/criterios_si inserts are idempotent (guarded by WHERE NOT EXISTS on slug).
// clasificaciones_si: TRUNCATE + reseed (old slugs no longer exist in the new 25-category set).
// software UPSERTS by slug (ON CONFLICT), so curated edits are reapplied instead of skipped.
// software_clasificaciones: per-tool junction inserts with ON CONFLICT DO NOTHING.
// Usage: node db/seed-to-sql.mjs

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const dir = dirname(fileURLToPath(import.meta.url))
const data = JSON.parse(readFileSync(join(dir, 'seed-content.json'), 'utf8'))

// Guard: slug is the software upsert key. A missing slug breaks ON CONFLICT, and a
// duplicate would silently overwrite a different tool. Fail loudly before emitting SQL.
const missingSlug = data.software.filter((s) => !s.slug).map((s) => s.nombre)
if (missingSlug.length > 0) {
  throw new Error(`Software entries missing "slug" in seed-content.json: ${missingSlug.join(', ')}`)
}
const softwareSlugs = data.software.map((s) => s.slug)
const dupeSlugs = [...new Set(softwareSlugs.filter((slug, i) => softwareSlugs.indexOf(slug) !== i))]
if (dupeSlugs.length > 0) {
  throw new Error(`Duplicate software slug(s) in seed-content.json: ${dupeSlugs.join(', ')}`)
}

const q = (v) => {
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'number') return String(v)
  return `'${String(v).replace(/'/g, "''")}'`
}
const qJson = (v) => `'${JSON.stringify(v ?? null).replace(/'/g, "''")}'::jsonb`

const lines = ['-- Generated by seed-to-sql.mjs from seed-content.json. Idempotent.', '']

// ── Temas — UPSERT by slug ────────────────────────────────────────────────────
// Upsert (not insert-if-absent) so reused slugs get their nombre/descripcion/orden
// refreshed when the roadmap is restructured. temas.slug is UNIQUE (temas_slug_key).
for (const t of data.temas) {
  lines.push(
    `insert into public.temas (slug, nombre, descripcion, orden)`,
    `values (${q(t.slug)}, ${q(t.nombre)}, ${q(t.descripcion)}, ${q(t.orden)})`,
    `on conflict (slug) do update set`,
    `  nombre = excluded.nombre, descripcion = excluded.descripcion, orden = excluded.orden;`,
    ''
  )
}

// ── Criterios SI (new — 7 axes) ───────────────────────────────────────────────
// Idempotent: skipped if slug already exists.
for (const cr of data.criterios) {
  lines.push(
    `insert into public.criterios_si (slug, nombre, descripcion, orden)`,
    `select ${q(cr.slug)}, ${q(cr.nombre)}, ${q(cr.descripcion)}, ${q(cr.orden)}`,
    `where not exists (select 1 from public.criterios_si where slug = ${q(cr.slug)});`,
    ''
  )
}

// ── Clasificaciones SI — TRUNCATE + reseed ────────────────────────────────────
// The old 9-category set (e.g. sistemas-expertos, redes-neuronales, algoritmos-geneticos)
// uses slugs that no longer exist in the new 25-category set. A slug-based WHERE NOT EXISTS
// guard cannot migrate those rows, so we TRUNCATE and reseed.
// CASCADE: the existing `limpiar_valoraciones_clasif` delete trigger auto-removes orphaned
// valoraciones rows. The software_clasificaciones junction (added by migration 009) also has
// ON DELETE CASCADE on clasificacion_si_id, so junction rows are cleaned up automatically.
// WARNING: this is a destructive, user-gated step — do not apply without explicit OK.
lines.push(
  `-- DESTRUCTIVE: removes all old clasificacion_si rows and their dependent valoraciones.`,
  `-- User-gated — applied only after explicit OK (S1-T09).`,
  `truncate public.clasificaciones_si cascade;`,
  ''
)

for (const c of data.clasificaciones_si) {
  lines.push(
    `insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)`,
    `select ${q(c.slug)}, ${q(c.nombre)}, ${q(c.en_que_consiste)}, ${q(c.imagen_url)}, ${q(c.ejemplos)}, ${qJson(c.enlaces)}, ${q(c.orden)}`,
    `where not exists (select 1 from public.clasificaciones_si where slug = ${q(c.slug)});`,
    ''
  )
}

// ── Wire criterio_id on each clasificacion ────────────────────────────────────
// Applied AFTER both criterios and clasificaciones are inserted.
// Safe because criterio_id is nullable at this point (SET NOT NULL happens in step 7,
// after this seed runs). Every category must receive its criterio_id here.
lines.push(`-- Wire criterio_id for all 25 categories (UPDATE after both insert blocks).`)
for (const c of data.clasificaciones_si) {
  lines.push(
    `update public.clasificaciones_si`,
    `set criterio_id = (select id from public.criterios_si where slug = ${q(c.criterio_slug)})`,
    `where slug = ${q(c.slug)};`,
    ''
  )
}

// ── Software — reduce to canonical 7 tools ────────────────────────────────────
// Production has 23 software rows. The seed authoritative set has only 7.
// The 16 retired tools (stockfish, swi-prolog, pygad, clips, apache-jena, scikit-learn,
// weka, yolo, tesseract-ocr, deap, heuristiclab, rasa, spacy, nltk, mediapipe,
// web-speech-api) are removed here.
// DELETE order: valoraciones before software (valoraciones has no FK; the trigger
// limpiar_valoraciones_software fires on DELETE of software rows, but we delete them
// explicitly first to be safe across idempotent re-runs).
// software_clasificaciones has ON DELETE CASCADE on software_id, so junction rows
// for deleted tools are removed automatically.
// WARNING: this is a destructive, user-gated step.
const keepSlugs = data.software.map((s) => s.slug)
const keepList = keepSlugs.map((slug) => q(slug)).join(', ')
lines.push(
  `-- DESTRUCTIVE: removes the 16 retired software rows and their dependent data.`,
  `-- User-gated — applied only after explicit OK (S1-T09).`,
  `-- valoraciones (no FK) are deleted first; software_clasificaciones cascade automatically.`,
  `delete from public.valoraciones`,
  `where contenido_tipo = 'software'`,
  `  and contenido_id in (select id from public.software where slug <> all(array[${keepList}]));`,
  ``,
  `delete from public.software where slug <> all(array[${keepList}]);`,
  ''
)

for (const s of data.software) {
  lines.push(
    `insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)`,
    `select ${q(s.slug)}, (select id from public.temas where slug = ${q(s.tema_slug)}),`,
    `  ${q(s.nombre)}, ${q(s.objetivo)}, ${q(s.descripcion_corta)}, ${q(s.url_acceso)}, ${q(s.licencia)}, ${q(s.anio_lanzamiento)}, ${q(s.autor_referencia)}, ${q(s.video_url)}, ${q(s.imagen_url)}`,
    `on conflict (slug) do update set`,
    `  tema_id = excluded.tema_id,`,
    `  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,`,
    `  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,`,
    `  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;`,
    ''
  )
}

// ── Temas — remove retired temas (destructive, user-gated) ────────────────────
// Must run AFTER the software upsert: software.tema_id is RESTRICT, and by now every
// tool has been re-pointed to a current tema, so retired temas have zero software.
// progreso_roadmap.tema_id is ON DELETE CASCADE, so user roadmap-progress rows for
// retired temas are removed automatically. WARNING: destructive — apply only after OK.
const keepTemaSlugs = data.temas.map((t) => t.slug)
const keepTemaList = keepTemaSlugs.map((slug) => q(slug)).join(', ')
lines.push(
  `-- DESTRUCTIVE: removes retired temas (and cascades their progreso_roadmap rows).`,
  `-- User-gated. Runs after the software upsert because software.tema_id is RESTRICT.`,
  `delete from public.temas where slug <> all(array[${keepTemaList}]);`,
  ''
)

// ── Software ↔ Clasificaciones SI junction ────────────────────────────────────
// Per software × each slug in clasificaciones_slugs[]: one row in software_clasificaciones.
// ON CONFLICT DO NOTHING makes this idempotent on re-runs.
lines.push(`-- Junction: software_clasificaciones (M2M, one row per tool × category).`)
for (const s of data.software) {
  for (const catSlug of (s.clasificaciones_slugs ?? [])) {
    lines.push(
      `insert into public.software_clasificaciones (software_id, clasificacion_si_id)`,
      `select`,
      `  (select id from public.software where slug = ${q(s.slug)}),`,
      `  (select id from public.clasificaciones_si where slug = ${q(catSlug)})`,
      `on conflict do nothing;`,
      ''
    )
  }
}

// ── Publicaciones — idempotent by slug ───────────────────────────────────────
// ON CONFLICT DO NOTHING: seeded posts are never overwritten; editorial edits
// made directly in the DB survive re-runs. autor_id is intentionally omitted
// (defaults to NULL; the UI shows an "Equipo ia-dex" fallback in that case).
// tema_id and clasificacion_si_id are resolved via subquery so FK integrity is
// guaranteed even across idempotent re-runs after the referenced rows exist.
lines.push(`-- Publicaciones (blog entries, idempotent by slug).`)
for (const p of (data.publicaciones ?? [])) {
  const temaIdExpr = p.tema_slug
    ? `(select id from public.temas where slug = ${q(p.tema_slug)})`
    : 'null'
  const clasificIdExpr = p.clasificacion_slug
    ? `(select id from public.clasificaciones_si where slug = ${q(p.clasificacion_slug)})`
    : 'null'
  lines.push(
    `insert into public.publicaciones (slug, titulo, cuerpo, imagen_url, video_url, enlaces, tema_id, clasificacion_si_id, estado)`,
    `values (`,
    `  ${q(p.slug)}, ${q(p.titulo)}, ${q(p.cuerpo)},`,
    `  ${q(p.imagen_url)}, ${q(p.video_url)}, ${qJson(p.enlaces)},`,
    `  ${temaIdExpr},`,
    `  ${clasificIdExpr},`,
    `  ${q(p.estado)}`,
    `)`,
    `on conflict (slug) do nothing;`,
    ''
  )
}

writeFileSync(join(dir, 'seed.sql'), lines.join('\n'))
console.log(
  `seed.sql written: ${data.temas.length} temas, ${data.criterios.length} criterios, ` +
  `${data.clasificaciones_si.length} clasificaciones, ${data.software.length} software, ` +
  `${data.software.reduce((n, s) => n + (s.clasificaciones_slugs?.length ?? 0), 0)} junction rows, ` +
  `${(data.publicaciones ?? []).length} publicaciones`
)
