-- Generated by seed-to-sql.mjs from seed-content.json. Idempotent.

insert into public.temas (slug, nombre, descripcion, orden)
select 'busqueda-resolucion-problemas', 'Búsqueda y resolución de problemas / juegos', 'Técnicas que permiten a un agente explorar un espacio de estados para encontrar una secuencia de acciones que lleve desde un estado inicial hasta un estado objetivo. Incluye búsqueda ciega (BFS, DFS), búsqueda heurística (A*) y algoritmos adversariales como minimax y poda alfa-beta, especialmente relevantes en juegos de dos jugadores.', 1
where not exists (select 1 from public.temas where slug = 'busqueda-resolucion-problemas');

insert into public.temas (slug, nombre, descripcion, orden)
select 'representacion-conocimiento', 'Representación del conocimiento y razonamiento', 'Área de la IA que estudia cómo codificar información sobre el mundo en estructuras que una computadora pueda usar para razonar. Incluye lógica de predicados, sistemas de reglas de producción, ontologías y bases de conocimiento, siendo la base de los sistemas expertos y la web semántica.', 2
where not exists (select 1 from public.temas where slug = 'representacion-conocimiento');

insert into public.temas (slug, nombre, descripcion, orden)
select 'aprendizaje-automatico', 'Aprendizaje automático', 'Conjunto de técnicas mediante las cuales un sistema mejora su desempeño a partir de la experiencia, sin ser programado explícitamente para cada tarea. Comprende el aprendizaje supervisado, no supervisado y por refuerzo, siendo la base del reconocimiento de imágenes, la recomendación y el procesamiento del lenguaje.', 3
where not exists (select 1 from public.temas where slug = 'aprendizaje-automatico');

insert into public.temas (slug, nombre, descripcion, orden)
select 'reconocimiento-patrones-vision', 'Reconocimiento de patrones / visión', 'Disciplina orientada a que las computadoras interpreten imágenes y video para identificar objetos, rostros, gestos y escenas. Combina técnicas de procesamiento de imágenes con redes neuronales convolucionales para tareas como detección de objetos, segmentación semántica y reconocimiento facial.', 4
where not exists (select 1 from public.temas where slug = 'reconocimiento-patrones-vision');

insert into public.temas (slug, nombre, descripcion, orden)
select 'algoritmos-geneticos-busqueda-local', 'Algoritmos genéticos y búsqueda local', 'Métodos de optimización inspirados en la evolución biológica (selección, cruce, mutación) y en procesos físicos como el recocido simulado. Se aplican a problemas de optimización combinatoria donde el espacio de búsqueda es demasiado grande para una exploración exhaustiva.', 5
where not exists (select 1 from public.temas where slug = 'algoritmos-geneticos-busqueda-local');

insert into public.temas (slug, nombre, descripcion, orden)
select 'bots-procesamiento-lenguaje-natural', 'Bots y procesamiento del lenguaje natural', 'Campo que estudia cómo las computadoras comprenden, generan y responden al lenguaje humano. Abarca desde el análisis sintáctico y semántico de texto hasta los modelos de lenguaje de gran escala y los chatbots conversacionales que se integran en servicios digitales.', 6
where not exists (select 1 from public.temas where slug = 'bots-procesamiento-lenguaje-natural');

insert into public.temas (slug, nombre, descripcion, orden)
select 'interaccion-hombre-maquina', 'Interacción Hombre-Máquina', 'Área interdisciplinaria que estudia el diseño, evaluación e implementación de sistemas interactivos para uso humano. Incorpora el reconocimiento de voz, gestos y lengua de señas como modalidades de entrada, permitiendo interfaces más naturales y accesibles entre personas y sistemas inteligentes.', 7
where not exists (select 1 from public.temas where slug = 'interaccion-hombre-maquina');

insert into public.criterios_si (slug, nombre, descripcion, orden)
select 'alcance-capacidad', 'Alcance y capacidad', 'Clasifica la IA según la amplitud de tareas que puede resolver, desde sistemas especializados hasta una hipotética inteligencia general.', 1
where not exists (select 1 from public.criterios_si where slug = 'alcance-capacidad');

insert into public.criterios_si (slug, nombre, descripcion, orden)
select 'russell-norvig', 'Modelos de Russell y Norvig', 'Las cuatro visiones clásicas de la IA según el cruce pensar/actuar y humano/racional.', 2
where not exists (select 1 from public.criterios_si where slug = 'russell-norvig');

insert into public.criterios_si (slug, nombre, descripcion, orden)
select 'evolucion-hintze', 'Evolución (Arend Hintze)', 'Niveles evolutivos de la IA según su capacidad de memoria, comprensión y conciencia.', 3
where not exists (select 1 from public.criterios_si where slug = 'evolucion-hintze');

insert into public.criterios_si (slug, nombre, descripcion, orden)
select 'tipo-aprendizaje', 'Tipo de aprendizaje (Machine Learning)', 'Cómo el sistema aprende a partir de los datos: con o sin etiquetas, por refuerzo o en profundidad.', 4
where not exists (select 1 from public.criterios_si where slug = 'tipo-aprendizaje');

insert into public.criterios_si (slug, nombre, descripcion, orden)
select 'paradigma-representacion', 'Paradigma de representación del conocimiento', 'Cómo se representa el conocimiento: con símbolos y reglas explícitas o de forma implícita en estructuras matemáticas.', 5
where not exists (select 1 from public.criterios_si where slug = 'paradigma-representacion');

insert into public.criterios_si (slug, nombre, descripcion, orden)
select 'naturaleza-conocimiento', 'Naturaleza y forma del conocimiento', 'Clasifica el conocimiento según su grado de abstracción, su expresabilidad y su contenido u objetivo.', 6
where not exists (select 1 from public.criterios_si where slug = 'naturaleza-conocimiento');

insert into public.criterios_si (slug, nombre, descripcion, orden)
select 'metodo-adquisicion', 'Método de adquisición del conocimiento', 'Cómo se obtiene el conocimiento: transferido por expertos humanos (deductivo) o extraído de datos y ejemplos (inductivo).', 7
where not exists (select 1 from public.criterios_si where slug = 'metodo-adquisicion');

-- DESTRUCTIVE: removes all old clasificacion_si rows and their dependent valoraciones.
-- User-gated — applied only after explicit OK (S1-T09).
truncate public.clasificaciones_si cascade;

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'ia-debil-estrecha', 'IA Débil (o Estrecha)', 'Diseñada para realizar tareas específicas y limitadas. No posee comprensión general del mundo. Es el tipo de IA utilizado actualmente.', null, 'Siri, Alexa, sistemas de reconocimiento de voz, recomendadores de contenido.', 'null'::jsonb, 1
where not exists (select 1 from public.clasificaciones_si where slug = 'ia-debil-estrecha');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'ia-fuerte-general', 'IA Fuerte (IAG)', 'Capaz de realizar cualquier tarea intelectual que pueda realizar un ser humano. Razonamiento general, adaptación y aprendizaje amplio. Actualmente es un concepto teórico.', null, '(concepto teórico — sin ejemplos implementados)', 'null'::jsonb, 2
where not exists (select 1 from public.clasificaciones_si where slug = 'ia-fuerte-general');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'sistemas-que-piensan-como-humanos', 'Sistemas que piensan como humanos', 'Según Russell y Norvig, este enfoque busca que las máquinas reproduzcan los procesos cognitivos humanos: cómo razonamos, tomamos decisiones y resolvemos problemas. Se apoya en la psicología cognitiva y la neurociencia para modelar la mente humana computacionalmente, siendo la base de la IA cognitiva y de los modelos de memoria y atención.', null, 'Sistemas de razonamiento analógico, modelos computacionales de la memoria humana, arquitecturas cognitivas como ACT-R.', '[{"titulo":"Artificial Intelligence: A Modern Approach — Sitio oficial AIMA","url":"https://aima.cs.berkeley.edu/"},{"titulo":"What is AI? The four schools of thought — Medium / Otto Lang","url":"https://otto-lang.medium.com/what-is-ai-an-explanation-by-the-4-different-schools-of-thought-74a85ebecda2"}]'::jsonb, 1
where not exists (select 1 from public.clasificaciones_si where slug = 'sistemas-que-piensan-como-humanos');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'sistemas-que-actuan-como-humanos', 'Sistemas que actúan como humanos', 'Este enfoque, también de Russell y Norvig, se centra en producir comportamientos indistinguibles de los humanos, independientemente de si el proceso interno es igual al humano. La prueba de Turing es el referente clásico de este paradigma. Incluye la robótica social, los avatares conversacionales y los sistemas de imitación de comportamiento humano.', null, 'Chatbots como ELIZA, robots humanoides sociales, asistentes de voz que imitan entonación humana.', '[{"titulo":"Artificial Intelligence: A Modern Approach — Sitio oficial AIMA","url":"https://aima.cs.berkeley.edu/"},{"titulo":"What is AI? The four schools of thought — Medium / Otto Lang","url":"https://otto-lang.medium.com/what-is-ai-an-explanation-by-the-4-different-schools-of-thought-74a85ebecda2"}]'::jsonb, 2
where not exists (select 1 from public.clasificaciones_si where slug = 'sistemas-que-actuan-como-humanos');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'sistemas-que-piensan-racionalmente', 'Sistemas que piensan racionalmente', 'Este enfoque busca formalizar el razonamiento correcto mediante la lógica y las matemáticas, siguiendo leyes de inferencia válidas para llegar a conclusiones garantizadas. Se basa en la tradición logicista de la filosofía y la matemática. Está en la base de los planificadores automáticos, los sistemas de demostración de teoremas y la programación lógica.', null, 'Prolog y sus motores de inferencia, demostradores automáticos de teoremas (Coq, Lean), planificadores PDDL.', '[{"titulo":"Artificial Intelligence: A Modern Approach — Sitio oficial AIMA","url":"https://aima.cs.berkeley.edu/"},{"titulo":"Logic and Artificial Intelligence — Stanford Encyclopedia of Philosophy","url":"https://plato.stanford.edu/entries/logic-ai/"}]'::jsonb, 3
where not exists (select 1 from public.clasificaciones_si where slug = 'sistemas-que-piensan-racionalmente');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'sistemas-que-actuan-racionalmente', 'Sistemas que actúan racionalmente', 'Es el enfoque preferido por Russell y Norvig: el agente racional actúa para maximizar su rendimiento esperado dado su conocimiento y sus capacidades, sin importar si lo hace exactamente como un humano o siguiendo un razonamiento lógico puro. Este paradigma unifica la teoría de decisiones, el aprendizaje por refuerzo y los agentes inteligentes.', null, 'Agentes de aprendizaje por refuerzo (AlphaGo, motores de ajedrez), robots autónomos, sistemas de recomendación.', '[{"titulo":"Artificial Intelligence: A Modern Approach — Sitio oficial AIMA","url":"https://aima.cs.berkeley.edu/"},{"titulo":"What is AI? The four schools of thought — Medium / Otto Lang","url":"https://otto-lang.medium.com/what-is-ai-an-explanation-by-the-4-different-schools-of-thought-74a85ebecda2"}]'::jsonb, 4
where not exists (select 1 from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'maquinas-reactivas', 'Máquinas Reactivas', 'No poseen memoria. Responden únicamente al estado actual del entorno. No aprenden de experiencias pasadas.', null, 'Deep Blue.', 'null'::jsonb, 1
where not exists (select 1 from public.clasificaciones_si where slug = 'maquinas-reactivas');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'memoria-limitada', 'Memoria Limitada', 'Utilizan información reciente para mejorar sus decisiones. Aprenden de experiencias previas.', null, 'Vehículos autónomos.', 'null'::jsonb, 2
where not exists (select 1 from public.clasificaciones_si where slug = 'memoria-limitada');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'teoria-de-la-mente', 'Teoría de la Mente', 'Comprenderían emociones, intenciones y necesidades humanas. Aún no existen plenamente.', null, '(concepto teórico)', 'null'::jsonb, 3
where not exists (select 1 from public.clasificaciones_si where slug = 'teoria-de-la-mente');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'autoconciencia', 'Autoconciencia', 'Poseerían conciencia de sí mismas y de su existencia. Concepto teórico.', null, '(concepto teórico)', 'null'::jsonb, 4
where not exists (select 1 from public.clasificaciones_si where slug = 'autoconciencia');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'aprendizaje-supervisado', 'Aprendizaje Supervisado', 'Aprende mediante datos etiquetados. Conoce previamente las respuestas correctas.', null, 'Filtros de spam, predicción de precios, diagnóstico asistido.', 'null'::jsonb, 1
where not exists (select 1 from public.clasificaciones_si where slug = 'aprendizaje-supervisado');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'aprendizaje-no-supervisado', 'Aprendizaje No Supervisado', 'Trabaja con datos sin etiquetar. Busca patrones y agrupaciones ocultas.', null, 'Clustering.', 'null'::jsonb, 2
where not exists (select 1 from public.clasificaciones_si where slug = 'aprendizaje-no-supervisado');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'aprendizaje-semi-supervisado', 'Aprendizaje Semi-supervisado', 'Combina datos etiquetados y no etiquetados. Reduce la necesidad de etiquetar grandes volúmenes.', null, 'Clasificación de páginas web con pocas etiquetas, reconocimiento de voz con audio parcialmente transcrito, detección de fraude con pocos casos confirmados.', 'null'::jsonb, 3
where not exists (select 1 from public.clasificaciones_si where slug = 'aprendizaje-semi-supervisado');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'aprendizaje-por-refuerzo', 'Aprendizaje por Refuerzo', 'Aprende mediante recompensas y castigos. Busca maximizar una recompensa acumulada.', null, 'AlphaGo.', 'null'::jsonb, 4
where not exists (select 1 from public.clasificaciones_si where slug = 'aprendizaje-por-refuerzo');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'deep-learning', 'Aprendizaje Profundo (Deep Learning)', 'Subcampo del ML. Redes neuronales profundas con múltiples capas.', null, 'Visión por computadora, PLN, reconocimiento de voz.', 'null'::jsonb, 5
where not exists (select 1 from public.clasificaciones_si where slug = 'deep-learning');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'ia-simbolica', 'IA Simbólica', 'La IA Simbólica representa el conocimiento mediante unidades discretas y explícitas: reglas lógicas, fórmulas, relaciones y símbolos manipulables. El razonamiento se lleva a cabo aplicando operaciones formales sobre estas estructuras, de manera que las decisiones pueden explicarse paso a paso. Es el paradigma dominante desde los orígenes de la IA hasta fines del siglo XX.', 'https://upload.wikimedia.org/wikipedia/commons/5/52/Chess_Programming.svg', 'Sistemas expertos médicos como MYCIN, demostradores automáticos de teoremas, planificadores lógicos como STRIPS.', '[{"titulo":"Inteligencia artificial simbólica — Wikipedia","url":"https://es.wikipedia.org/wiki/Inteligencia_artificial_simb%C3%B3lica"},{"titulo":"Logic and Artificial Intelligence — Stanford Encyclopedia of Philosophy","url":"https://plato.stanford.edu/entries/logic-ai/"}]'::jsonb, 1
where not exists (select 1 from public.clasificaciones_si where slug = 'ia-simbolica');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'ia-subsimbolica', 'IA Sub-simbólica', 'La IA Sub-simbólica (o no simbólica) codifica el conocimiento de forma implícita, distribuida en los pesos y parámetros de estructuras como las redes neuronales. En lugar de reglas explícitas, el sistema aprende representaciones internas a partir de grandes cantidades de datos. Esta aproximación es la base del deep learning y es más robusta ante datos ruidosos o incompletos.', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg', 'Redes neuronales convolucionales para visión artificial, modelos de lenguaje como GPT, redes recurrentes para series temporales.', '[{"titulo":"Symbolic vs. Sub-symbolic AI — Wikipedia (Symbolic AI, sección de contraste)","url":"https://en.wikipedia.org/wiki/Symbolic_artificial_intelligence"},{"titulo":"Red neuronal artificial — Wikipedia en español","url":"https://es.wikipedia.org/wiki/Red_neuronal_artificial"}]'::jsonb, 2
where not exists (select 1 from public.clasificaciones_si where slug = 'ia-subsimbolica');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'conocimiento-teorico', 'Conocimiento Teórico', 'Basado en teorías, modelos y generalizaciones. Busca explicar fenómenos. (dimensión: grado de abstracción)', null, 'Las leyes de Newton aplicadas a simulación física, un modelo matemático del clima, la teoría de grafos para optimización de rutas.', 'null'::jsonb, 1
where not exists (select 1 from public.clasificaciones_si where slug = 'conocimiento-teorico');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'conocimiento-empirico', 'Conocimiento Empírico', 'Basado en la experiencia directa y la observación. Surge de casos prácticos. (dimensión: grado de abstracción)', null, 'Datos de sensores de una planta industrial, registros históricos de ventas, observaciones clínicas acumuladas.', 'null'::jsonb, 2
where not exists (select 1 from public.clasificaciones_si where slug = 'conocimiento-empirico');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'conocimiento-explicito', 'Conocimiento Explícito', 'Fácil de documentar, almacenar y transmitir. (dimensión: expresabilidad)', null, 'Manuales, procedimientos, bases de conocimiento.', 'null'::jsonb, 3
where not exists (select 1 from public.clasificaciones_si where slug = 'conocimiento-explicito');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'conocimiento-tacito', 'Conocimiento Tácito', 'Difícil de expresar formalmente. Basado en experiencia e intuición. (dimensión: expresabilidad)', null, 'Reconocer una cara familiar.', 'null'::jsonb, 4
where not exists (select 1 from public.clasificaciones_si where slug = 'conocimiento-tacito');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'conocimiento-declarativo', 'Conocimiento Declarativo', 'Describe hechos, conceptos o relaciones. Responde qué es verdadero o falso (¿Qué?). (dimensión: contenido y objetivo)', null, 'Una base de hechos (''París es la capital de Francia''), una ontología de productos, una red semántica de relaciones.', 'null'::jsonb, 5
where not exists (select 1 from public.clasificaciones_si where slug = 'conocimiento-declarativo');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'conocimiento-procedimental', 'Conocimiento Procedimental', 'Describe procesos y métodos. Explica cómo realizar una tarea (¿Cómo?). (dimensión: contenido y objetivo)', null, 'El algoritmo de ordenamiento de una lista, los pasos de un protocolo de diagnóstico, una receta paso a paso.', 'null'::jsonb, 6
where not exists (select 1 from public.clasificaciones_si where slug = 'conocimiento-procedimental');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'aprendizaje-deductivo', 'Aprendizaje Deductivo', 'El conocimiento es transferido directamente por expertos humanos. Característico de los sistemas expertos. Basado en reglas definidas manualmente.', null, 'Sistemas expertos como MYCIN, motores de reglas de negocio, bases de conocimiento con reglas if-then definidas por especialistas.', 'null'::jsonb, 1
where not exists (select 1 from public.clasificaciones_si where slug = 'aprendizaje-deductivo');

insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)
select 'aprendizaje-inductivo', 'Aprendizaje Inductivo', 'El sistema extrae conocimiento a partir de datos y ejemplos. Característico de Machine Learning, redes neuronales, minería de datos.', null, 'Un clasificador de spam entrenado con miles de correos, un modelo de visión que aprende de ejemplos etiquetados, árboles de decisión sobre datos históricos.', 'null'::jsonb, 2
where not exists (select 1 from public.clasificaciones_si where slug = 'aprendizaje-inductivo');

-- Wire criterio_id for all 25 categories (UPDATE after both insert blocks).
update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'alcance-capacidad')
where slug = 'ia-debil-estrecha';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'alcance-capacidad')
where slug = 'ia-fuerte-general';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'russell-norvig')
where slug = 'sistemas-que-piensan-como-humanos';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'russell-norvig')
where slug = 'sistemas-que-actuan-como-humanos';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'russell-norvig')
where slug = 'sistemas-que-piensan-racionalmente';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'russell-norvig')
where slug = 'sistemas-que-actuan-racionalmente';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'evolucion-hintze')
where slug = 'maquinas-reactivas';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'evolucion-hintze')
where slug = 'memoria-limitada';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'evolucion-hintze')
where slug = 'teoria-de-la-mente';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'evolucion-hintze')
where slug = 'autoconciencia';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'tipo-aprendizaje')
where slug = 'aprendizaje-supervisado';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'tipo-aprendizaje')
where slug = 'aprendizaje-no-supervisado';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'tipo-aprendizaje')
where slug = 'aprendizaje-semi-supervisado';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'tipo-aprendizaje')
where slug = 'aprendizaje-por-refuerzo';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'tipo-aprendizaje')
where slug = 'deep-learning';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'paradigma-representacion')
where slug = 'ia-simbolica';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'paradigma-representacion')
where slug = 'ia-subsimbolica';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'naturaleza-conocimiento')
where slug = 'conocimiento-teorico';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'naturaleza-conocimiento')
where slug = 'conocimiento-empirico';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'naturaleza-conocimiento')
where slug = 'conocimiento-explicito';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'naturaleza-conocimiento')
where slug = 'conocimiento-tacito';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'naturaleza-conocimiento')
where slug = 'conocimiento-declarativo';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'naturaleza-conocimiento')
where slug = 'conocimiento-procedimental';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'metodo-adquisicion')
where slug = 'aprendizaje-deductivo';

update public.clasificaciones_si
set criterio_id = (select id from public.criterios_si where slug = 'metodo-adquisicion')
where slug = 'aprendizaje-inductivo';

-- DESTRUCTIVE: removes the 16 retired software rows and their dependent data.
-- User-gated — applied only after explicit OK (S1-T09).
-- valoraciones (no FK) are deleted first; software_clasificaciones cascade automatically.
delete from public.valoraciones
where contenido_tipo = 'software'
  and contenido_id in (select id from public.software where slug <> all(array['gymnasium', 'protege', 'tensorflow', 'opencv', 'or-tools', 'chatgpt', 'whisper']));

delete from public.software where slug <> all(array['gymnasium', 'protege', 'tensorflow', 'opencv', 'or-tools', 'chatgpt', 'whisper']);

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'gymnasium', (select id from public.temas where slug = 'busqueda-resolucion-problemas'),
  'Gymnasium (ex OpenAI Gym)', 'Plataforma estándar para desarrollar y comparar algoritmos de aprendizaje por refuerzo mediante entornos simulados.', 'Gymnasium provee una API unificada para entornos de RL (CartPole, MuJoCo, Atari) que permite entrenar agentes capaces de resolver tareas de búsqueda y control mediante prueba y error. Es el estándar de facto en investigación de reinforcement learning.', 'https://gymnasium.farama.org/', 'MIT', 2016, 'OpenAI / Farama Foundation', 'https://www.youtube.com/watch?v=FvuyrpzvwdI', null
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'protege', (select id from public.temas where slug = 'representacion-conocimiento'),
  'Protégé', 'Editor de ontologías OWL de uso libre para construir bases de conocimiento reutilizables en la web semántica.', 'Protégé es el editor de ontologías más utilizado en investigación y educación, desarrollado por Stanford University. Permite crear, visualizar y razonar sobre ontologías OWL, siendo la base de aplicaciones en bioinformática, biomedicina y web semántica.', 'https://protege.stanford.edu/', 'BSD-2', 1999, 'Stanford Center for Biomedical Informatics Research', 'https://www.youtube.com/watch?v=vHmC-rRuMYM', 'https://upload.wikimedia.org/wikipedia/commons/7/72/Prot%C3%A9g%C3%A9_Logo.gif'
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'tensorflow', (select id from public.temas where slug = 'aprendizaje-automatico'),
  'TensorFlow', 'Plataforma de código abierto para construir y entrenar modelos de aprendizaje automático y redes neuronales a escala.', 'TensorFlow es el framework de deep learning de Google, ampliamente utilizado en investigación y producción. Ofrece un ecosistema completo que incluye Keras como API de alto nivel, herramientas de despliegue en dispositivos móviles (TF Lite) y en navegadores (TF.js).', 'https://www.tensorflow.org/', 'Apache 2.0', 2015, 'Google Brain Team', 'https://www.youtube.com/watch?v=tPYj3fFJGjk', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg'
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'opencv', (select id from public.temas where slug = 'reconocimiento-patrones-vision'),
  'OpenCV', 'Biblioteca de visión por computadora de código abierto para procesar imágenes, detectar objetos y analizar video en tiempo real.', 'OpenCV (Open Computer Vision Library) es la biblioteca de visión artificial más usada en el mundo, con más de 2 500 algoritmos optimizados. Soporta C++, Python y Java, y se integra con frameworks de deep learning para tareas como reconocimiento facial, detección de movimiento y reconstrucción 3D.', 'https://opencv.org/', 'Apache 2.0', 1999, 'Intel Corporation / OpenCV Foundation', 'https://www.youtube.com/watch?v=oXlwWbU8l2o', 'https://upload.wikimedia.org/wikipedia/commons/5/53/OpenCV_Logo_with_text.png'
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'or-tools', (select id from public.temas where slug = 'algoritmos-geneticos-busqueda-local'),
  'OR-Tools', 'Suite de optimización combinatoria de Google para resolver problemas de ruteo de vehículos, planificación, programación entera y restricciones.', 'OR-Tools es la suite de optimización de código abierto de Google, ganadora del campeonato internacional de programación por restricciones desde 2013. Disponible en Python, C++, Java y C#, cubre resolución de problemas de ruteo (VRP), scheduling, bin packing y programación lineal entera.', 'https://developers.google.com/optimization', 'Apache 2.0', 2010, 'Google', 'https://www.youtube.com/watch?v=D5y4meQmKyE', null
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'chatgpt', (select id from public.temas where slug = 'bots-procesamiento-lenguaje-natural'),
  'ChatGPT', 'Asistente conversacional de propósito general basado en modelos de lenguaje de gran escala (LLMs), accesible vía web.', 'ChatGPT es el chatbot de OpenAI construido sobre los modelos GPT-4 y GPT-4o. Permite mantener conversaciones en lenguaje natural, escribir código, resumir textos y responder preguntas complejas. Es el ejemplo más reconocido de IA generativa conversacional en la actualidad.', 'https://chatgpt.com/', 'Propietaria (acceso gratuito con límites)', 2022, 'OpenAI', 'https://www.youtube.com/watch?v=_LMKslv5hPY', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/ChatGPT-Logo.svg'
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

insert into public.software (slug, tema_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)
select 'whisper', (select id from public.temas where slug = 'interaccion-hombre-maquina'),
  'Whisper (OpenAI)', 'Sistema de reconocimiento de voz automático de código abierto con soporte multilingüe y alta robustez ante ruido y acentos.', 'Whisper es un modelo de reconocimiento de voz de OpenAI entrenado en 680 000 horas de audio diverso. Soporta reconocimiento y traducción en múltiples idiomas, incluyendo español. Es de código abierto (MIT) y puede ejecutarse localmente o a través de la API de OpenAI.', 'https://github.com/openai/whisper', 'MIT', 2022, 'OpenAI', 'https://www.youtube.com/watch?v=HbY51mVKrcE', 'https://upload.wikimedia.org/wikipedia/commons/6/66/OpenAI_logo_2025_%28symbol%29.svg'
on conflict (slug) do update set
  tema_id = excluded.tema_id,
  nombre = excluded.nombre, objetivo = excluded.objetivo, descripcion_corta = excluded.descripcion_corta,
  url_acceso = excluded.url_acceso, licencia = excluded.licencia, anio_lanzamiento = excluded.anio_lanzamiento,
  autor_referencia = excluded.autor_referencia, video_url = excluded.video_url, imagen_url = excluded.imagen_url;

-- Junction: software_clasificaciones (M2M, one row per tool × category).
insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'gymnasium'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'gymnasium'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'gymnasium'),
  (select id from public.clasificaciones_si where slug = 'memoria-limitada')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'gymnasium'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-por-refuerzo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'gymnasium'),
  (select id from public.clasificaciones_si where slug = 'ia-subsimbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'gymnasium'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-inductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'gymnasium'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-empirico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'gymnasium'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'protege'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'protege'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-piensan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'protege'),
  (select id from public.clasificaciones_si where slug = 'maquinas-reactivas')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'protege'),
  (select id from public.clasificaciones_si where slug = 'ia-simbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'protege'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-deductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'protege'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-declarativo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'protege'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-explicito')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'memoria-limitada')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'deep-learning')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-supervisado')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'ia-subsimbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-inductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-empirico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'tensorflow'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'maquinas-reactivas')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-supervisado')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'deep-learning')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'ia-subsimbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-inductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-empirico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'opencv'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'or-tools'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'or-tools'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'or-tools'),
  (select id from public.clasificaciones_si where slug = 'maquinas-reactivas')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'or-tools'),
  (select id from public.clasificaciones_si where slug = 'ia-simbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'or-tools'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-deductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'or-tools'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'or-tools'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-teorico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-como-humanos')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'memoria-limitada')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-supervisado')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-por-refuerzo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'deep-learning')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'ia-subsimbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-inductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-empirico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'chatgpt'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-tacito')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'ia-debil-estrecha')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'sistemas-que-actuan-racionalmente')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'memoria-limitada')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-supervisado')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'deep-learning')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'ia-subsimbolica')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'aprendizaje-inductivo')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-empirico')
on conflict do nothing;

insert into public.software_clasificaciones (software_id, clasificacion_si_id)
select
  (select id from public.software where slug = 'whisper'),
  (select id from public.clasificaciones_si where slug = 'conocimiento-procedimental')
on conflict do nothing;
