// Generates db/seed.sql from db/seed-content.json.
// Inserts are idempotent (guarded by WHERE NOT EXISTS on slug/nombre),
// so re-running the output SQL never duplicates rows.
// Usage: node db/seed-to-sql.mjs

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const dir = dirname(fileURLToPath(import.meta.url))
const data = JSON.parse(readFileSync(join(dir, 'seed-content.json'), 'utf8'))

const q = (v) => {
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'number') return String(v)
  return `'${String(v).replace(/'/g, "''")}'`
}
const qJson = (v) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`

const lines = ['-- Generated by seed-to-sql.mjs from seed-content.json. Idempotent.', '']

for (const t of data.temas) {
  lines.push(
    `insert into public.temas (slug, nombre, descripcion, orden)`,
    `select ${q(t.slug)}, ${q(t.nombre)}, ${q(t.descripcion)}, ${q(t.orden)}`,
    `where not exists (select 1 from public.temas where slug = ${q(t.slug)});`,
    ''
  )
}

for (const c of data.clasificaciones_si) {
  lines.push(
    `insert into public.clasificaciones_si (slug, nombre, en_que_consiste, imagen_url, ejemplos, enlaces, orden)`,
    `select ${q(c.slug)}, ${q(c.nombre)}, ${q(c.en_que_consiste)}, ${q(c.imagen_url)}, ${q(c.ejemplos)}, ${qJson(c.enlaces)}, ${q(c.orden)}`,
    `where not exists (select 1 from public.clasificaciones_si where slug = ${q(c.slug)});`,
    ''
  )
}

for (const s of data.software) {
  const clasSelect = s.clasificacion_slug
    ? `(select id from public.clasificaciones_si where slug = ${q(s.clasificacion_slug)})`
    : 'null'
  lines.push(
    `insert into public.software (tema_id, clasificacion_si_id, nombre, objetivo, descripcion_corta, url_acceso, licencia, anio_lanzamiento, autor_referencia, video_url, imagen_url)`,
    `select (select id from public.temas where slug = ${q(s.tema_slug)}), ${clasSelect},`,
    `  ${q(s.nombre)}, ${q(s.objetivo)}, ${q(s.descripcion_corta)}, ${q(s.url_acceso)}, ${q(s.licencia)}, ${q(s.anio_lanzamiento)}, ${q(s.autor_referencia)}, ${q(s.video_url)}, ${q(s.imagen_url)}`,
    `where not exists (select 1 from public.software where nombre = ${q(s.nombre)});`,
    ''
  )
}

writeFileSync(join(dir, 'seed.sql'), lines.join('\n'))
console.log(`seed.sql written: ${data.temas.length} temas, ${data.clasificaciones_si.length} clasificaciones, ${data.software.length} software`)
